In [1]:
import numpy as np

In [2]:
print("Hello WOrld")

Hello WOrld


In [6]:
myarr=np.array([[3,1,6,4,8]])
print(myarr)

[[3 1 6 4 8]]


In [7]:
myarr[0,1]

1

In [9]:
myarr.shape

(1, 5)

In [10]:
myarr.dtype

dtype('int32')

In [13]:
listarray=np.array([[3,1,8],[4,9,7],[0,2,4]])

In [14]:
listarray[1,2]

7

In [15]:
listarray[2,0]

0

In [16]:
listarray.shape

(3, 3)

In [17]:
listarray.size

9

In [18]:
listarray.dtype

dtype('int32')

In [19]:
lspace=np.linspace(1,5,4)

In [20]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [21]:
lspace.dtype

dtype('float64')

In [22]:
lspace.shape

(4,)

In [23]:
emp=np.empty((4,6))

In [24]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.24612081e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 9.79094971e-307,
        6.89804133e-307, 1.11261162e-306, 8.34443015e-308]])

In [26]:
arr=np.arange(99)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr[2]=23

In [30]:
arr

array([ 0,  1, 23,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr.reshape(3,33)

array([[ 0,  1, 23,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr=arr.ravel

In [33]:
arr

<function ndarray.ravel>

# Numpy Axix

In [34]:
x=[[2,4,1],[3,7,9],[3,6,1]]
arr=np.array(x)   

In [ ]:
## in 1D array axis=0 and in 2D array axis=0, axis=1

In [35]:
arr

array([[2, 4, 1],
       [3, 7, 9],
       [3, 6, 1]])

In [36]:
arr.sum(axis=0)

array([ 8, 17, 11])

In [37]:
arr.sum(axis=1)

array([ 7, 19, 10])

In [40]:
arr.T ##Transpose

array([[2, 3, 3],
       [4, 7, 6],
       [1, 9, 1]])

In [42]:
for item in arr.flat:
    print(item)

2
4
1
3
7
9
3
6
1


In [44]:
arr.nbytes ##total bites consumed

36

In [47]:
OneDaaray=np.array([4,8,2,34,1])
OneDaaray.argmax()   ##shows index of maximum elemnent

3

In [48]:
OneDaaray=np.array([4,8,2,34,1])
OneDaaray.argmin()   ##shows index of min elemnent

4

In [49]:
OneDaaray.argsort() ##shows the indexes of sort numbers

array([4, 2, 0, 1, 3], dtype=int64)

In [50]:
TwoDarray=np.array([[3,2,1],[5,8,4],[9,2,1]])
TwoDarray.argmin()

2

In [51]:
TwoDarray=np.array([[3,2,1],[5,8,4],[9,2,1]])
TwoDarray.argmax()

6

In [52]:
TwoDarray=np.array([[3,2,1],
                    [5,8,4],
                    [9,2,1]])
TwoDarray.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [53]:
TwoDarray=np.array([[3,2,1],
                    [5,8,4],
                    [9,2,1]])
TwoDarray.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [54]:
TwoDarray=np.array([[3,2,1],
                    [5,8,4],
                    [9,2,1]])
TwoDarray.argmin(axis=1)

array([2, 2, 2], dtype=int64)

In [60]:
TwoDarray.reshape(3,3)  ## this will basically shape the matrix into following rows, columns format

array([[3, 2, 1],
       [5, 8, 4],
       [9, 2, 1]])

In [61]:
aa1=np.array([[1,2,3],[3,2,1],[3,5,1]])

In [62]:
aa2=np.array([[0,1,2],[2,4,2],[0,5,3]])

In [63]:
aa1+aa2

array([[ 1,  3,  5],
       [ 5,  6,  3],
       [ 3, 10,  4]])

In [64]:
aa1-aa2

array([[ 1,  1,  1],
       [ 1, -2, -1],
       [ 3,  0, -2]])

In [65]:
aa1*aa2

array([[ 0,  2,  6],
       [ 6,  8,  2],
       [ 0, 25,  3]])

In [67]:
np.sqrt(aa1)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 1.41421356, 1.        ],
       [1.73205081, 2.23606798, 1.        ]])

In [69]:
aa1.sum()

21

In [70]:
aa1.min()

1

In [71]:
np.where(aa1>3) #shows index where values are greater than 3

(array([2], dtype=int64), array([1], dtype=int64))

In [73]:
np.count_nonzero(aa2)

7

# Storage difference bw numpy array and python array

In [76]:
import sys

In [74]:
py_arr=[3,2,14]

In [77]:
np_arr=np.array(py_arr)

In [78]:
sys.getsizeof(1)* len(py_arr)

84

In [80]:
np_arr.itemsize * np_arr.size

12

In [81]:
myarr=np.array([9,8,7])
print(myarr)

[9 8 7]


In [83]:
for i in myarr:
    print(i)

9
8
7


In [85]:
myarr[1]

8